Only post benchmark comment if it failed or recovered

diff --git a/.github/workflows/benchmark.yml b/.github/workflows/benchmark.yml
--- a/.github/workflows/benchmark.yml
+++ b/.github/workflows/benchmark.yml
@@ -24,12 +24,15 @@ jobs:
       # POC -- should not be blocking yet until benchmarks are stable and can be used to block PRs
       - name: Run Benchmark
         id: cob
+        # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#custom-shell
+        shell: bash {0}
+        continue-on-error: true
         run: |
           out=$(mktemp -q)
-          (
-            # set -o pipefail # uncommit to enable failing checks for making benchmarks worse
-            cob --base origin/main 2>&1 | tee $out
-          )
+          set -o pipefail # causes exit code from cob to bubble up from tee
+          cob --base origin/main 2>&1 | tee $out
+          EXIT_CODE=$?
+
           # https://github.community/t/set-output-truncates-multiline-strings/16852/3
           # also remove colors, which don't translate in the github comment
           result="$(cat $out | sed -e 's/\x1B\[1;91m/-/g' -e 's/\x1B\[0m\s//g' -e 's/\x1B\[1;34m/\+/g')"
@@ -37,6 +40,8 @@ jobs:
           result="${result//$'\n'/'%0A'}"
           result="${result//$'\r'/'%0D'}"
           echo "::set-output name=result::$result"
+          echo "::set-output name=exit_code::$EXIT_CODE"
+          exit $EXIT_CODE
 
       - name: Find Comment
         uses: peter-evans/find-comment@v1
@@ -46,9 +51,9 @@ jobs:
           comment-author: 'github-actions[bot]'
           body-includes: <!-- cob-output -->
 
-      - name: Create or update comment
+      - name: Create or update comment if cob failed
         uses: peter-evans/create-or-update-comment@v1
-        if: ${{ steps.cob.outputs.result != '' }}
+        if: steps.cob.outputs.exit_code != '0'
         with:
           comment-id: ${{ steps.comment.outputs.comment-id }}
           issue-number: ${{ github.event.pull_request.number }}
@@ -56,7 +61,24 @@ jobs:
             <!-- cob-output -->
             ### Benchmark comparison to `origin/main`
 
-            _This is currently only informational_
+            _This is currently only informational, but your PR may have a negative performance impact_
+
+            ```
+            ${{ steps.cob.outputs.result }}
+            ```
+          edit-mode: replace
+
+      - name: Update comment if cob succeeded
+        uses: peter-evans/create-or-update-comment@v1
+        if: steps.comment.outputs.comment-id != '' && steps.cob.outputs.exit_code == '0'
+        with:
+          comment-id: ${{ steps.comment.outputs.comment-id }}
+          issue-number: ${{ github.event.pull_request.number }}
+          body: |
+            <!-- cob-output -->
+            ### Benchmark comparison to `origin/main`
+
+            _This is currently only informational, your PR previously reported a negative performance impact that appears to have been resolved_
 
             ```
             ${{ steps.cob.outputs.result }}
